"""Export utilities for saving generated content"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT


class ExportManager:
    """Manage export of generated content to various formats"""

    EXPORT_DIR = "exports"

    def __init__(self, export_dir: str = EXPORT_DIR):
        self.export_dir = export_dir
        self._create_export_directory()

    def _create_export_directory(self):
        """Create export directory if it doesn't exist"""
        Path(self.export_dir).mkdir(exist_ok=True)

    def _sanitize_filename(self, filename: str) -> str:
        """Sanitize filename to avoid invalid characters"""
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            filename = filename.replace(char, "_")
        return filename

    def _generate_filename(self, content_type: str, extension: str) -> str:
        """Generate filename with timestamp"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        sanitized_type = self._sanitize_filename(content_type).replace(" ", "_")
        return f"{sanitized_type}_{timestamp}.{extension}"

    def export_txt(
        self, content: str, filename: Optional[str] = None, metadata: dict = None
    ) -> str:
        """Export content as TXT file"""

        if not filename:
            filename = self._generate_filename("content", "txt")
        else:
            filename = self._sanitize_filename(filename) + ".txt"

        filepath = os.path.join(self.export_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            if metadata:
                f.write("=" * 60 + "\n")
                f.write("CONTENT METADATA\n")
                f.write("=" * 60 + "\n")
                for key, value in metadata.items():
                    f.write(f"{key}: {value}\n")
                f.write("=" * 60 + "\n\n")

            f.write(content)

        return filepath

    def export_docx(
        self, content: str, filename: Optional[str] = None, metadata: dict = None
    ) -> str:
        """Export content as DOCX file"""

        if not filename:
            filename = self._generate_filename("content", "docx")
        else:
            filename = self._sanitize_filename(filename) + ".docx"

        filepath = os.path.join(self.export_dir, filename)

        # Create document
        doc = Document()

        # Add title
        title = doc.add_paragraph()
        title_run = title.add_run("AI Generated Content")
        title_run.font.size = Pt(24)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(0, 102, 204)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add metadata if provided
        if metadata:
            doc.add_paragraph()
            doc.add_heading("Metadata", level=2)

            for key, value in metadata.items():
                p = doc.add_paragraph()
                p.add_run(f"{key}: ").bold = True
                p.add_run(str(value))

            doc.add_paragraph()
            doc.add_paragraph("-" * 60)
            doc.add_paragraph()

        # Add content
        for paragraph_text in content.split("\n\n"):
            if paragraph_text.strip():
                p = doc.add_paragraph(paragraph_text.strip())
                p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

        # Add footer with generation info
        doc.add_paragraph()
        footer_text = f"\n\nGenerated by ContentForge - AI Content Generator\n{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"

        footer_p = doc.add_paragraph(footer_text)
        footer_p_format = footer_p.paragraph_format
        footer_p_format.space_before = Pt(12)

        for run in footer_p.runs:
            run.font.size = Pt(8)
            run.font.italic = True
            run.font.color.rgb = RGBColor(128, 128, 128)

        doc.save(filepath)
        return filepath

    def export_pdf(
        self, content: str, filename: Optional[str] = None, metadata: dict = None
    ) -> str:
        """Export content as PDF file"""

        if not filename:
            filename = self._generate_filename("content", "pdf")
        else:
            filename = self._sanitize_filename(filename) + ".pdf"

        filepath = os.path.join(self.export_dir, filename)

        # Create PDF document
        doc = SimpleDocTemplate(filepath, pagesize=letter, topMargin=0.75 * inch)

        # Container for PDF elements
        elements = []

        # Get default stylesheet
        styles = getSampleStyleSheet()

        # Custom title style
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=RGBColor(0, 102, 204),
            spaceAfter=30,
            alignment=TA_LEFT,
        )

        # Add title
        elements.append(Paragraph("AI Generated Content", title_style))
        elements.append(Spacer(1, 0.3 * inch))

        # Add metadata if provided
        if metadata:
            meta_style = ParagraphStyle(
                "Metadata",
                parent=styles["Normal"],
                fontSize=10,
                textColor=RGBColor(64, 64, 64),
                spaceAfter=6,
            )

            elements.append(Paragraph("<b>Content Information</b>", styles["Heading2"]))
            elements.append(Spacer(1, 0.1 * inch))

            for key, value in metadata.items():
                elements.append(
                    Paragraph(f"<b>{key}:</b> {str(value)}", meta_style)
                )

            elements.append(Spacer(1, 0.3 * inch))
            elements.append(Paragraph("_" * 80, styles["Normal"]))
            elements.append(Spacer(1, 0.3 * inch))

        # Add content
        content_style = ParagraphStyle(
            "Content",
            parent=styles["BodyText"],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceAfter=12,
        )

        for paragraph_text in content.split("\n\n"):
            if paragraph_text.strip():
                elements.append(Paragraph(paragraph_text.strip(), content_style))
                elements.append(Spacer(1, 0.1 * inch))

        # Add footer
        elements.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle(
            "Footer",
            parent=styles["Normal"],
            fontSize=8,
            textColor=RGBColor(128, 128, 128),
            alignment=TA_LEFT,
        )

        elements.append(Paragraph("_" * 80, footer_style))
        elements.append(Spacer(1, 0.1 * inch))
        footer_text = f"Generated by ContentForge • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        elements.append(Paragraph(footer_text, footer_style))

        # Build PDF
        doc.build(elements)
        return filepath

    def export_multiple_outputs(
        self,
        outputs: list,
        content_type: str,
        filename_prefix: Optional[str] = None,
        format: str = "txt",
    ) -> list:
        """Export multiple outputs to separate files"""

        filepaths = []

        for idx, output in enumerate(outputs):
            if filename_prefix:
                filename = (
                    f"{self._sanitize_filename(filename_prefix)}_v{idx + 1}.{format}"
                )
            else:
                filename = self._generate_filename(f"{content_type}_v{idx + 1}", format)

            if format.lower() == "txt":
                filepath = self.export_txt(output, filename)
            elif format.lower() == "docx":
                filepath = self.export_docx(output, filename)
            elif format.lower() == "pdf":
                filepath = self.export_pdf(output, filename)
            else:
                filepath = self.export_txt(output, filename)

            filepaths.append(filepath)

        return filepaths

    def get_export_files(self) -> list:
        """Get list of all exported files"""

        files = []
        if os.path.exists(self.export_dir):
            for filename in os.listdir(self.export_dir):
                filepath = os.path.join(self.export_dir, filename)
                if os.path.isfile(filepath):
                    size = os.path.getsize(filepath)
                    modified_time = datetime.fromtimestamp(
                        os.path.getmtime(filepath)
                    ).strftime("%Y-%m-%d %H:%M:%S")
                    files.append(
                        {
                            "filename": filename,
                            "filepath": filepath,
                            "size": size,
                            "modified": modified_time,
                        }
                    )

        return sorted(files, key=lambda x: x["modified"], reverse=True)

    def delete_export_file(self, filename: str) -> bool:
        """Delete an export file"""

        filepath = os.path.join(self.export_dir, filename)

        try:
            if os.path.exists(filepath):
                os.remove(filepath)
                return True
        except Exception:
            pass

        return False

    def open_export_folder(self) -> str:
        """Return path to export folder"""
        return os.path.abspath(self.export_dir)
